[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.3.0"
leptos_abort = { path = ".."}
wasm-bindgen-futures = "0.4.36"
web-sys = {version = "0.3.63", features=["RequestInit"]}
